# Use the official Golang image as a base image
FROM golang:1.24.2

# Set the working directory inside the container
WORKDIR /app

# Copy the source code into the container
COPY . .

# Build the Go application
RUN go build -o main .

# Expose the port that the application listens on
EXPOSE 8080

# Command to run the executable
CMD ["/main"]
